export const LIST_ITEMS = 'LIST_ITEMS';
export const FETCH_ITEMS = 'FETCH_ITEMS'
export const PAYMENT_TRANSACTION = 'PAYMENT_TRANSACTION';
export const PAYMENT_FAILED = 'PAYMENT_FAILED';
export const CHECKOUT_LOADER = 'CHECKOUT_LOADER';